# Generated by Django 5.1.3 on 2024-12-11 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=10)),
                ('market', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('dividend_date', models.DateTimeField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.action')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Achat'), ('SELL', 'Vente'), ('DIV', 'Dividende')], max_length=4)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_share', models.FloatField()),
                ('transaction_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.action')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.portfolio')),
            ],
        ),
    ]
