# Generated by Django 5.1.3 on 2024-12-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_action_portfolio_dividend_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='action',
            name='description',
        ),
        migrations.RemoveField(
            model_name='action',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='dividend',
            name='dividend_date',
        ),
    ]
