# Generated by Django 5.1.3 on 2024-12-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0003_remove_action_created_at_remove_action_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='notes',
        ),
    ]
