# Generated by Django 5.1.3 on 2024-12-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0004_remove_transaction_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
